In [1]:
import torch
import pandas as pd
import torch.nn as nn
import numpy as np



import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
inputs = pd.read_csv('heart.csv')
targets = inputs.pop('target')

inputs = np.array(inputs)
targets = np.array(targets)

print(inputs)
print(targets)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [3]:
no_samples,no_features = inputs.shape
no_features

13

In [4]:
inputs_train,inputs_test,targets_train,targets_test = train_test_split(inputs, targets, test_size=0.33)

In [5]:
# scaling data
inputs_train = StandardScaler().fit_transform(inputs_train)
inputs_test = StandardScaler().fit_transform(inputs_test)


In [6]:
inputs_train = torch.from_numpy(inputs_train.astype(np.float32))
inputs_test = torch.from_numpy(inputs_test.astype(np.float32))
targets_train = torch.from_numpy(targets_train.astype(np.float32))
targets_test = torch.from_numpy(targets_test.astype(np.float32))

In [7]:
targets_train = targets_train.reshape(-1,1)
targets_test = targets_test.reshape(-1,1)

targets_train.shape

torch.Size([203, 1])

In [8]:
class LogisticRegression(nn.Module):
    def __init__(self):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(13,1)

    def forward(self, targets_train ):
        out = self.linear(targets_train)
        targets_preds = torch.sigmoid(out)
        return targets_preds

model = LogisticRegression()
        
    

In [9]:
model

LogisticRegression(
  (linear): Linear(in_features=13, out_features=1, bias=True)
)

In [10]:
loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


In [49]:
num_epochs = 1500

In [52]:
for epoch in range(num_epochs):
    targets_preds = model(inputs_train)
    loss = loss_fn(targets_preds,targets_train)

    loss.backward()

    optimizer.step()
    optimizer.zero_grad()

    
    

    if(epoch+1)%10 == 0:
        with torch.no_grad():
            targets_preds = model(inputs_test)
            targets_preds_cls = targets_preds.round()
            acc = targets_preds_cls.eq(targets_test).sum() / float(inputs_test.shape[0])
        
            print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}, ACC: {acc*100}')

Epoch: 10, Loss: 0.3405, ACC: 87.0
Epoch: 20, Loss: 0.3405, ACC: 87.0
Epoch: 30, Loss: 0.3405, ACC: 87.0
Epoch: 40, Loss: 0.3405, ACC: 87.0
Epoch: 50, Loss: 0.3405, ACC: 87.0
Epoch: 60, Loss: 0.3405, ACC: 87.0
Epoch: 70, Loss: 0.3405, ACC: 87.0
Epoch: 80, Loss: 0.3405, ACC: 87.0
Epoch: 90, Loss: 0.3405, ACC: 87.0
Epoch: 100, Loss: 0.3405, ACC: 87.0
Epoch: 110, Loss: 0.3405, ACC: 87.0
Epoch: 120, Loss: 0.3405, ACC: 87.0
Epoch: 130, Loss: 0.3405, ACC: 87.0
Epoch: 140, Loss: 0.3405, ACC: 87.0
Epoch: 150, Loss: 0.3405, ACC: 87.0
Epoch: 160, Loss: 0.3405, ACC: 87.0
Epoch: 170, Loss: 0.3405, ACC: 87.0
Epoch: 180, Loss: 0.3405, ACC: 87.0
Epoch: 190, Loss: 0.3405, ACC: 87.0
Epoch: 200, Loss: 0.3405, ACC: 87.0
Epoch: 210, Loss: 0.3405, ACC: 87.0
Epoch: 220, Loss: 0.3405, ACC: 87.0
Epoch: 230, Loss: 0.3405, ACC: 87.0
Epoch: 240, Loss: 0.3405, ACC: 87.0
Epoch: 250, Loss: 0.3405, ACC: 87.0
Epoch: 260, Loss: 0.3405, ACC: 87.0
Epoch: 270, Loss: 0.3405, ACC: 87.0
Epoch: 280, Loss: 0.3405, ACC: 87.0
E

In [48]:
torch.save(model.state_dict(),'heart_attack_data.pth')

In [13]:

# def predict_heart_attack(age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal):
#     inputs = [age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal]

#     mean = [54.366336633663366, 0.6831683168316832, 0.966996699669967, 131.62376237623764, 246.26402640264027, 
#             0.1485148514851485, 0.528052805280528, 149.64686468646866, 0.32673267326732675, 1.0396039603960396,
#             1.3993399339933994, 0.7293729372937293, 2.3135313531353137]
#     std =  [9.067101638577872, 0.46524119304834577, 1.0303480250839463, 17.509178065734393, 51.74515101045713,
#             0.3556096038825341, 0.5249911240963214, 22.86733258188924, 0.46901858543869346, 1.1591574732421364,
#             0.6152084301256651, 1.0209175011165652, 0.6112653149988239]

#     for i in range(len(mean)):
#         inputs[i] = (inputs[i] - mean[i])/ std[i]

#     inputs = torch.from_numpy(np.array(inputs).astype(np.float32))

#     pre_model = LogisticRegression()
#     pre_model.load_state_dict(torch.load('heart_attack_data.pth'))

#     preds = pre_model(inputs)
#     ans = "None"
#     if preds.item() >= 0.5:
#         ans = "YES"
#         chance = round(preds.item()*100,2)
#     else:
#         ans = "NO"
#         chance = round(100 - (preds.item()*100),2)
    


#     return ans , chance
# values = [57,1,0,152,274,0,1,88,1,1.2,1,1,3]
# print(predict_heart_attack(*values))