In [10]:
import torch

In [11]:
x = torch.randn(3, requires_grad=True)
x

tensor([-0.9157,  1.3448, -1.0181], requires_grad=True)

In [12]:
y = x+2
y

tensor([1.0843, 3.3448, 0.9819], grad_fn=<AddBackward0>)

In [14]:
z = y.mean()
z

tensor(1.8037, grad_fn=<MeanBackward0>)

In [17]:
z.backward()
print(x.grad)

tensor([0.6667, 0.6667, 0.6667])
