In [35]:
import torch
import pandas as pd
import torch.nn as nn
import numpy as np



import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [36]:
inputs = pd.read_csv('heart.csv')
targets = inputs.pop('target')

inputs = np.array(inputs)
targets = np.array(targets)

print(inputs)
print(targets)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [37]:
no_samples,no_features = inputs.shape
no_features

13

In [38]:
inputs_train,inputs_test,targets_train,targets_test = train_test_split(inputs, targets, test_size=0.33)

In [39]:
# scaling data
inputs_train = StandardScaler().fit_transform(inputs_train)
inputs_test = StandardScaler().fit_transform(inputs_test)


In [40]:
inputs_train = torch.from_numpy(inputs_train.astype(np.float32))
inputs_test = torch.from_numpy(inputs_test.astype(np.float32))
targets_train = torch.from_numpy(targets_train.astype(np.float32))
targets_test = torch.from_numpy(targets_test.astype(np.float32))

In [41]:
targets_train = targets_train.reshape(-1,1)
targets_test = targets_test.reshape(-1,1)

targets_train.shape

torch.Size([203, 1])

In [42]:
class LogisticRegression(nn.Module):
    def __init__(self):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(13,1)

    def forward(self, targets_train ):
        out = self.linear(targets_train)
        targets_preds = torch.sigmoid(out)
        return targets_preds

   



model = LogisticRegression()
        
    

In [43]:
model

LogisticRegression(
  (linear): Linear(in_features=13, out_features=1, bias=True)
)

In [44]:
loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


In [45]:
num_epochs = 300

In [ ]:
for epoch in range(num_epochs):
    targets_preds = model(inputs_train)
    loss = loss_fn(targets_preds,targets_train)

    loss.backward()

    optimizer.step()
    optimizer.zero_grad()

    
    

    if(epoch+1)%10 == 0:
        with torch.no_grad():
            targets_preds = model(inputs_test)
            targets_preds_cls = targets_preds.round()
            acc = targets_preds_cls.eq(targets_test).sum() / float(inputs_test.shape[0])
        
            print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}, ACC: {acc*100}')

Epoch: 10, Loss: 0.6757, ACC: 63.0
Epoch: 20, Loss: 0.6498, ACC: 61.0
Epoch: 30, Loss: 0.6267, ACC: 64.0
Epoch: 40, Loss: 0.6063, ACC: 68.0
Epoch: 50, Loss: 0.5880, ACC: 71.0
Epoch: 60, Loss: 0.5718, ACC: 74.0
Epoch: 70, Loss: 0.5572, ACC: 75.0
Epoch: 80, Loss: 0.5441, ACC: 75.0
Epoch: 90, Loss: 0.5322, ACC: 75.0
Epoch: 100, Loss: 0.5216, ACC: 77.0
Epoch: 110, Loss: 0.5119, ACC: 78.0
Epoch: 120, Loss: 0.5031, ACC: 81.0
Epoch: 130, Loss: 0.4951, ACC: 81.0
Epoch: 140, Loss: 0.4878, ACC: 82.0
Epoch: 150, Loss: 0.4812, ACC: 82.0
Epoch: 160, Loss: 0.4750, ACC: 82.0
Epoch: 170, Loss: 0.4694, ACC: 84.0
Epoch: 180, Loss: 0.4642, ACC: 83.0
Epoch: 190, Loss: 0.4594, ACC: 84.0
Epoch: 200, Loss: 0.4549, ACC: 84.0
Epoch: 210, Loss: 0.4508, ACC: 84.0
Epoch: 220, Loss: 0.4470, ACC: 84.0
Epoch: 230, Loss: 0.4434, ACC: 84.0
Epoch: 240, Loss: 0.4401, ACC: 85.0
Epoch: 250, Loss: 0.4370, ACC: 85.0
Epoch: 260, Loss: 0.4341, ACC: 85.0
Epoch: 270, Loss: 0.4314, ACC: 85.0
Epoch: 280, Loss: 0.4289, ACC: 85.0
E