In [53]:
import torch.nn as nn
import torch
import numpy as np

In [54]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

In [55]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [56]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [57]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [58]:
from torch.utils.data import TensorDataset


In [59]:
#define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [60]:
from torch.utils.data import DataLoader

In [61]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [62]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 68.,  96.,  71.],
        [ 74.,  66.,  43.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[104., 118.],
        [ 57.,  69.],
        [119., 133.],
        [ 56.,  70.],
        [103., 119.]])


In [63]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5720, -0.0652,  0.1586],
        [-0.1937,  0.1402,  0.0187]], requires_grad=True)
Parameter containing:
tensor([0.2074, 0.3568], requires_grad=True)


In [64]:
#parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5720, -0.0652,  0.1586],
         [-0.1937,  0.1402,  0.0187]], requires_grad=True),
 Parameter containing:
 tensor([0.2074, 0.3568], requires_grad=True)]

In [65]:
#generate predictions
preds = model(inputs)
preds

tensor([[ 44.4110,  -3.5864],
        [ 56.6676,  -3.7359],
        [ 50.4269,   3.3734],
        [ 61.6119, -12.6796],
        [ 44.5143,   1.7590],
        [ 45.0482,  -3.9202],
        [ 56.8915,  -3.8573],
        [ 51.1575,   3.1985],
        [ 60.9747, -12.3457],
        [ 44.1010,   1.9714],
        [ 44.6349,  -3.7078],
        [ 57.3048,  -4.0698],
        [ 50.2031,   3.4948],
        [ 62.0253, -12.8920],
        [ 43.8771,   2.0929]], grad_fn=<AddmmBackward>)

In [66]:
#loss function
import torch.nn.functional as F


In [67]:
#define loss func
loss_fn = F.mse_loss

In [68]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(5980.1514, grad_fn=<MseLossBackward>)


In [69]:
#optimizer for reducing loss
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

#function to train the model

In [70]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    #repeat for given num of epochs
    for epoch in range(num_epochs):

        #train eith batches
        for xb, yb in train_dl:

            #generate pred
            pred = model(xb)
            #calculate loss
            loss = loss_fn(pred, yb)
            #compute grads
            loss.backward()
            #update params
            opt.step()
            #reset
            opt.zero_grad()
        if(epoch+1)%10 ==0:
            print('Epoch [{}/{}], loss:{:.4f}'.format(epoch+1, num_epochs, loss.item()))




In [71]:
fit(1000, model, loss_fn, opt, train_dl)

Epoch [10/1000], loss:187.5248
Epoch [20/1000], loss:386.3076
Epoch [30/1000], loss:157.4374
Epoch [40/1000], loss:194.2688
Epoch [50/1000], loss:48.1316
Epoch [60/1000], loss:65.0690
Epoch [70/1000], loss:97.0144
Epoch [80/1000], loss:40.5357
Epoch [90/1000], loss:22.2931
Epoch [100/1000], loss:30.8861
Epoch [110/1000], loss:26.8448
Epoch [120/1000], loss:19.6711
Epoch [130/1000], loss:17.0721
Epoch [140/1000], loss:15.8594
Epoch [150/1000], loss:22.0430
Epoch [160/1000], loss:13.1338
Epoch [170/1000], loss:8.1241
Epoch [180/1000], loss:12.5732
Epoch [190/1000], loss:6.8497
Epoch [200/1000], loss:6.4336
Epoch [210/1000], loss:6.7053
Epoch [220/1000], loss:12.2080
Epoch [230/1000], loss:5.0378
Epoch [240/1000], loss:7.0024
Epoch [250/1000], loss:3.6916
Epoch [260/1000], loss:6.2312
Epoch [270/1000], loss:4.0334
Epoch [280/1000], loss:10.2790
Epoch [290/1000], loss:3.5964
Epoch [300/1000], loss:1.8095
Epoch [310/1000], loss:2.9698
Epoch [320/1000], loss:4.7609
Epoch [330/1000], loss:4.3

In [72]:
preds = model(inputs)
preds

tensor([[ 57.0249,  70.5084],
        [ 81.9255, 100.3478],
        [118.4761, 133.2391],
        [ 20.9098,  37.8835],
        [101.6495, 118.1510],
        [ 55.7743,  69.4230],
        [ 81.7587, 100.4056],
        [118.7559, 133.8170],
        [ 22.1604,  38.9689],
        [102.7333, 119.2942],
        [ 56.8582,  70.5662],
        [ 80.6749,  99.2625],
        [118.6429, 133.1813],
        [ 19.8260,  36.7403],
        [102.9001, 119.2364]], grad_fn=<AddmmBackward>)

In [73]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [74]:
model(torch.tensor([[75,63,44.]]))

tensor([[53.5084, 67.5928]], grad_fn=<AddmmBackward>)