In [1]:
import torch
import numpy as np 

Tensor to nupy

In [2]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [3]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

Numpy to tensor

In [4]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [5]:
y = torch.from_numpy(x)
y

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

Using gpu

In [6]:
if torch.cuda.is_available():
    mydevice = torch.device("cuda")
    p = torch.ones(5,5, device=mydevice)

