In [1]:
import torch

In [2]:
x = torch.rand(5,3)
x

tensor([[0.9235, 0.0540, 0.5947],
        [0.4433, 0.3464, 0.7156],
        [0.8214, 0.6027, 0.3349],
        [0.0919, 0.4903, 0.3856],
        [0.9545, 0.8440, 0.1861]])

In [3]:
print(x[:, 0])

tensor([0.9235, 0.4433, 0.8214, 0.0919, 0.9545])


In [4]:
print(x[0,:])

tensor([0.9235, 0.0540, 0.5947])


In [5]:
print(x[1,1])

tensor(0.3464)
