In [1]:
import torch

In [2]:
x = torch.rand(2,2)
x

tensor([[0.8347, 0.9769],
        [0.8433, 0.0737]])

In [3]:
y = torch.ones(2,2, dtype=torch.int32)
y
print(y.size())

torch.Size([2, 2])


In [4]:
z = torch.tensor([2,1])
z

tensor([2, 1])

Basic operations

In [5]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [6]:
a

tensor([[0.5272, 0.8865],
        [0.8314, 0.7510]])

In [7]:
b

tensor([[0.2200, 0.3601],
        [0.5354, 0.3311]])

In [8]:
# addition
c = a+b
c

tensor([[0.7471, 1.2465],
        [1.3668, 1.0821]])

In [9]:
# addition second method
b.add_(x)
b

tensor([[1.0546, 1.3370],
        [1.3786, 0.4048]])

In [10]:
#addition third method
p = torch.add(x, y)
p

tensor([[1.8347, 1.9769],
        [1.8433, 1.0737]])